### ISSUE TITLE
Click on public data collection taken to LabCAS login page

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#182] opened 2023-11-07 19:54 UTC
## 🐛 Describe the Bug

When clicking on a public data collection for the first time. It takes me to the LabCAS login page.

From Data page - https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/data/
Click on Autoantibody Biomarkers
There are times when I'm taken to the LabCAS login page, but other times when I'm taken directly to the data collection.

I can't seem to replicate consistently, but wanted to note it. Sorry! 
<img width="1414" alt="Screenshot 2023-11-07 at 11 34 30 AM" src="https://github.com/EDRN/P5/assets/58526347/7dd7053c-2a96-424f-ad12-063ea21cdab8">

**Comment by yuliujpl** [comment] 2024-05-01 23:22
hmm, can't replicate it in incognito nor regular mode. Please let me know when this happens again!

**Comment by nutjob4life** [comment] 2024-05-02 14:03
Closing as "cannot reproduce" but feel free to re-open (with reproduction steps if possible) if it re-appears

**Closed as completed by nutjob4life** 2024-05-02 14:03 UTC
Labels: 🐛bug, 🙅cannot reproduce
